import type { ProjectsContent } from './types';

// This file is auto-generated by scripts/generate-huggingface-projects.mjs.
export const projects: ProjectsContent = {
  "generatedAt": "2026-03-17T18:49:40.689Z",
  "groups": [
    {
      "id": "anzhc",
      "title": "Personal",
      "sourceHref": "https://huggingface.co/Anzhc",
      "moreCount": 5,
      "moreHref": "https://huggingface.co/Anzhc/models",
      "items": [
        {
          "id": "Anzhc/Anzhcs-VAEs",
          "name": "Anzhcs-VAEs",
          "repoPath": "Anzhc/Anzhcs-VAEs",
          "href": "https://huggingface.co/Anzhc/Anzhcs-VAEs",
          "description": "Collection of VAE(Variational Autoencoder) models, experiments, and finetunes, particularly for SDXL, targeting improved visuals for generations.",
          "monthlyDownloads": 157728
        },
        {
          "id": "Anzhc/Anzhcs_YOLOs",
          "name": "Anzhcs_YOLOs",
          "repoPath": "Anzhc/Anzhcs_YOLOs",
          "href": "https://huggingface.co/Anzhc/Anzhcs_YOLOs",
          "description": "Collection of YOLO models, encompassing detection, segmentation, classification and their downstream usage. Includes models made specifically for Adetailer, scoring models, narrow taggers and other utility applications.",
          "monthlyDownloads": 82412
        },
        {
          "id": "Anzhc/MS-LC-EQ-D-VR_VAE",
          "name": "MS-LC-EQ-D-VR_VAE",
          "repoPath": "Anzhc/MS-LC-EQ-D-VR_VAE",
          "href": "https://huggingface.co/Anzhc/MS-LC-EQ-D-VR_VAE",
          "description": "An SDXL VAE lineup reproducing results of the EQ-VAE paper, while applying few fixes proposed in VIVAT paper. Significantly outperforming original SDXL vae and other EQ VAEs known at the time, while requiring relatively low compute to train.",
          "monthlyDownloads": 1654
        },
        {
          "id": "Anzhc/Z-Image_Anime_VAE",
          "name": "Z-Image_Anime_VAE",
          "repoPath": "Anzhc/Z-Image_Anime_VAE",
          "href": "https://huggingface.co/Anzhc/Z-Image_Anime_VAE",
          "description": "A Decoder-only finetune of the Flux1 VAE(Z-Image uses Flux 1 VAE), reducing oversharpening and jpeg artifacts of the original, helping anime art generation.",
          "monthlyDownloads": 1101
        },
        {
          "id": "Anzhc/Noobai11-CLIP-L-and-BigG-Anime-Text-Encoders",
          "name": "Noobai11-CLIP-L-and-BigG-Anime-Text-Encoders",
          "repoPath": "Anzhc/Noobai11-CLIP-L-and-BigG-Anime-Text-Encoders",
          "href": "https://huggingface.co/Anzhc/Noobai11-CLIP-L-and-BigG-Anime-Text-Encoders",
          "description": "Special project testing text encoders in Noobai model, their performance in retrieval task, and finetuning them on an anime-specific dataset, as well as showcasing performance on the token count well beyond architectural limit of 77. (Refer to Posts section for full research)",
          "monthlyDownloads": 1624
        },
        {
          "id": "Anzhc/SDXL-Text-Encoder-Longer-CLIP-L",
          "name": "SDXL-Text-Encoder-Longer-CLIP-L",
          "repoPath": "Anzhc/SDXL-Text-Encoder-Longer-CLIP-L",
          "href": "https://huggingface.co/Anzhc/SDXL-Text-Encoder-Longer-CLIP-L",
          "description": "Experimental finetune on smaller dataset, consisting of data only with 225 or more tokens, essentially pinning CLIP to 3+ chunks. Benchmarks show that CLIP is capable of retrieval far beyond its limits, even at the range of 300 and even 400 tokens.",
          "monthlyDownloads": 188
        }
      ]
    },
    {
      "id": "cabal-research",
      "title": "Cabal Research",
      "sourceHref": "https://huggingface.co/CabalResearch",
      "moreCount": 3,
      "moreHref": "https://huggingface.co/CabalResearch/models",
      "items": [
        {
          "id": "CabalResearch/NoobAI-Flux2VAE-RectifiedFlow-0.3",
          "name": "NoobAI-Flux2VAE-RectifiedFlow-0.3",
          "repoPath": "CabalResearch/NoobAI-Flux2VAE-RectifiedFlow-0.3",
          "href": "https://huggingface.co/CabalResearch/NoobAI-Flux2VAE-RectifiedFlow-0.3",
          "description": "Direct continuation of NoobAI-Flux2VAE-RectifiedFlow, improving upon the earlier Prototype.",
          "monthlyDownloads": 1425
        },
        {
          "id": "CabalResearch/NoobAI-Flux2VAE-RectifiedFlow",
          "name": "NoobAI-Flux2VAE-RectifiedFlow",
          "repoPath": "CabalResearch/NoobAI-Flux2VAE-RectifiedFlow",
          "href": "https://huggingface.co/CabalResearch/NoobAI-Flux2VAE-RectifiedFlow",
          "description": "Experimental architecture of an SDXL model using new VAE, bringing 32 channel latents to the arch. An early Prototype, trained in a tight budget.",
          "monthlyDownloads": 115
        }
      ]
    },
    {
      "id": "chenkin-rf",
      "title": "ChenkinRF",
      "sourceHref": "https://huggingface.co/ChenkinRF",
      "moreCount": 1,
      "moreHref": "https://huggingface.co/ChenkinRF/models",
      "items": [
        {
          "id": "ChenkinRF/ChenkinNoob-XL-v0.3-Rectified-Flow",
          "name": "ChenkinNoob-XL-v0.3-Rectified-Flow",
          "repoPath": "ChenkinRF/ChenkinNoob-XL-v0.3-Rectified-Flow",
          "href": "https://huggingface.co/ChenkinRF/ChenkinNoob-XL-v0.3-Rectified-Flow",
          "description": "Continuation of ChenkinNoob-XL-v0.2-Rectified-Flow, particularly improving character knowledge, sharpness and stability of the model.",
          "monthlyDownloads": 1602
        },
        {
          "id": "ChenkinRF/ChenkinNoob-XL-v0.2-Rectified-Flow",
          "name": "ChenkinNoob-XL-v0.2-Rectified-Flow",
          "repoPath": "ChenkinRF/ChenkinNoob-XL-v0.2-Rectified-Flow",
          "href": "https://huggingface.co/ChenkinRF/ChenkinNoob-XL-v0.2-Rectified-Flow",
          "description": "Initial conversion of Chenkin model from eps prediction to rectified flow.",
          "monthlyDownloads": 1547
        }
      ]
    }
  ]
};
